#version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres_traspasos_r1
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app_traspasos_r1
    ports:
      - "5432:5432"
    volumes:
      - traspasos_r1_bdd:/var/lib/postgresql/data
    networks:
      - traspasos_net

  api:
    image: api-traspasos-v1
    container_name: api_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traspasos_net
    depends_on:
      - postgres

volumes:
  traspasos_r1_bdd:
    external: true

networks:
  traspasos_net:
    driver: bridge
